version: '3'

services:
  #dependency
  todo-redis:
    image: redis:5.0.3
    container_name: redis
    ports:
      - 6379:6379

  todo-elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300      

  todo-postgres:
    container_name: postgres
    build: ./todo-postgres
    image: postgres:1.0
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo1234
    ports:
      - 5432:5432      

  # api 
  todo-api:
    container_name: todo-api
    build: ./todo-api
    ports:
      - 3000:3000
    command: sh /src/start.sh
    volumes:
      - .:/src/todo-api
      - /src/todo-api/node_modules
    environment:
      - POSTGRES_HOST=todo-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo1234
      - REDIS_HOST=todo-redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=todo-elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on:
      - todo-redis
      - todo-elasticsearch
      - todo-postgres      

  # frontend
  todo-view:
    container_name: todo-view
    build: ./todo-view
    ports:
      - 4300:4300
    volumes:
      - .:/src/todo-view
      - /src/todo-view/node_modules
    environment:
      - PORT=4300
    depends_on:
      - todo-api

  # nginx proxy
  todo-proxy:
    container_name: todo-proxy
    build:
      context: ./todo-proxy
    ports:
      - 8080:80
    depends_on:
      - todo-api
      - todo-view